import time
import uuid


TEST_DATA_PREFIX = "TEST_AUTO_"


def generate_random_isbn() -> str:
    return f"{TEST_DATA_PREFIX}ISBN_{uuid.uuid4().hex[:12]}"


def generate_unique_title() -> str:
    timestamp = int(time.time() * 1000)
    suffix = uuid.uuid4().hex[:8]
    return f"{TEST_DATA_PREFIX}Book_{timestamp}_{suffix}"


def generate_test_book_payload() -> dict:
    title = generate_unique_title()

    return {
        "title": title,
        "author": "API Automation",
        "isbn": generate_random_isbn(),
        "genre": "Testing",
        "description": f"{title} generated by api-tests.",
        "language": "English",
        "shelfLocation": "TEST-AUTO-01",
        "totalCopies": 1,
        "availableCopies": 1,
    }
